general.import = [ "~/.config/omarchy/current/theme/alacritty.toml" ]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "Adwaita Mono" }
bold = { family = "Adwaita Mono" }
italic = { family = "Adwaita Mono" }
size = 11

[window]
padding.x = 14
padding.y = 14
decorations = "None"

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]
